### ISSUE TITLE
uhh you got any instructions bro?

### ISSUE THREAD

**Issue by brickyosu** [funcy2267/GD-nong-downloader#1]
idfk how to use this

**Comment by KalAle20** [comment]
hey idk if you still need help but
1. you edit line 24 of main.py and remove the +".mp3"
2. then you run the build.bat file
3. you go into the newly created dist folder and run the executable
hope this helps :)

edit:
also make sure to install all the python packages required in the requirements.txt file with pip

**Comment by brickyosu** [comment]
thx man

**Comment by funcyme** [comment]
instructions are now in readme
